# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 33) do

  create_table "ask_authorized_users", :force => true do |t|
    t.column "user_id",           :integer
    t.column "authority_type_id", :integer
    t.column "is_valid",          :integer,  :default => 1, :null => false
    t.column "expired_at",        :datetime
    t.column "editor_id",         :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "ask_blocked_ips", :force => true do |t|
    t.column "ip",         :string,   :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_operations", :force => true do |t|
    t.column "name",        :string,   :default => "", :null => false
    t.column "description", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_score_orders", :force => true do |t|
    t.column "operation_id",    :integer,  :null => false
    t.column "operation_score", :integer,  :null => false
    t.column "version",         :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_search_keywords", :force => true do |t|
    t.column "area_id",    :integer,                  :null => false
    t.column "type_id",    :integer,                  :null => false
    t.column "keyword",    :string,   :default => "", :null => false
    t.column "user_id",    :integer
    t.column "ip",         :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_tag_links", :force => true do |t|
    t.column "start_id",    :integer,  :null => false
    t.column "end_id",      :integer,  :null => false
    t.column "link_weight", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_tieba_topic_posts", :force => true do |t|
    t.column "tieba_topic_id", :integer,                 :null => false
    t.column "user_id",        :integer
    t.column "content",        :text
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_tieba_topics", :force => true do |t|
    t.column "area_id",      :integer,                  :null => false
    t.column "tieba_id",     :integer,                  :null => false
    t.column "user_id",      :integer,                  :null => false
    t.column "tag_id",       :integer,                  :null => false
    t.column "subject",      :string,   :default => "", :null => false
    t.column "method",       :integer,                  :null => false
    t.column "is_delete",    :integer,  :default => 0,  :null => false
    t.column "post_counter", :integer,  :default => 1,  :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_tiebas", :force => true do |t|
    t.column "area_id",      :integer,                  :null => false
    t.column "user_id",      :integer,                  :null => false
    t.column "name",         :string,   :default => "", :null => false
    t.column "company_name", :string,   :default => "", :null => false
    t.column "description",  :string
    t.column "sign",         :string
    t.column "icon_url",     :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_topic_reads", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "topic_type_id", :integer,  :null => false
    t.column "topic_id",      :integer,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_topic_subscriptions", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "topic_type_id", :integer,  :null => false
    t.column "topic_id",      :integer,  :null => false
    t.column "guest_email",   :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_topic_tag_urls", :force => true do |t|
    t.column "tag_id",         :integer,  :null => false
    t.column "topic_url",      :string
    t.column "topic_url_type", :string
    t.column "topic_id",       :integer
    t.column "topic_type_id",  :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_topic_user_tags", :force => true do |t|
    t.column "user_tag_id",   :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
  end

  create_table "ask_user_infos", :force => true do |t|
    t.column "user_id",    :integer,  :null => false
    t.column "nickname",   :string
    t.column "sex",        :string
    t.column "sign",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_user_operations", :force => true do |t|
    t.column "user_id",         :integer,  :null => false
    t.column "operation_id",    :integer,  :null => false
    t.column "operation_count", :integer,  :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_user_scores", :force => true do |t|
    t.column "user_id",    :integer,                   :null => false
    t.column "score",      :integer,  :default => 100, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_user_tags", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_user_tags", ["id"], :name => "index_user_tag_id", :unique => true
  add_index "ask_user_tags", ["name"], :name => "index_user_tag_name"

  create_table "ask_zhidao_editor_topics", :force => true do |t|
    t.column "editor_id",       :integer
    t.column "zhidao_topic_id", :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_zhidao_editor_uploads", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "flag",         :integer,  :default => 0
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_zhidao_topic_post_votes", :force => true do |t|
    t.column "zhidao_topic_post_id", :integer,  :null => false
    t.column "user_id",              :integer,  :null => false
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
  end

  create_table "ask_zhidao_topic_posts", :force => true do |t|
    t.column "zhidao_topic_id", :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "content",         :text
    t.column "vote_counter",    :integer,  :default => 1, :null => false
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                 :null => false
    t.column "editor_id",       :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
  end

  add_index "ask_zhidao_topic_posts", ["id"], :name => "index_zhidao_topic_post_id", :unique => true

  create_table "ask_zhidao_topics", :force => true do |t|
    t.column "area_id",       :integer,                  :null => false
    t.column "user_id",       :integer
    t.column "tag_id",        :integer
    t.column "subject",       :string,   :default => "", :null => false
    t.column "method",        :integer,                  :null => false
    t.column "description",   :text
    t.column "is_delete",     :integer,  :default => 0,  :null => false
    t.column "is_close",      :integer,  :default => 0,  :null => false
    t.column "best_post_id",  :integer
    t.column "post_counter",  :integer,  :default => 1,  :null => false
    t.column "is_vote",       :integer,  :default => 0,  :null => false
    t.column "vote_counter",  :integer,  :default => 1,  :null => false
    t.column "score",         :integer,  :default => 0,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
    t.column "is_distribute", :integer,  :default => 0
    t.column "source",        :string
    t.column "source_id",     :integer
    t.column "view_counter",  :integer,  :default => 1,  :null => false
    t.column "guest_email",   :string
    t.column "ip",            :string
  end

  add_index "ask_zhidao_topics", ["id"], :name => "index_zhidao_topic_id", :unique => true
  add_index "ask_zhidao_topics", ["subject"], :name => "index_zhidao_topic_subject"

  create_table "ask_zhishi_topic_posts", :force => true do |t|
    t.column "zhishi_topic_id", :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "content",         :text
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                 :null => false
    t.column "editor_id",       :integer
  end

  add_index "ask_zhishi_topic_posts", ["id"], :name => "index_zhishi_topic_post_id", :unique => true

  create_table "ask_zhishi_topics", :force => true do |t|
    t.column "area_id",       :integer,                  :null => false
    t.column "user_id",       :integer
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "tag_id",        :integer
    t.column "subject",       :string,   :default => "", :null => false
    t.column "method",        :integer,                  :null => false
    t.column "description",   :text
    t.column "reference",     :string
    t.column "is_delete",     :integer,  :default => 0,  :null => false
    t.column "is_close",      :integer,  :default => 0,  :null => false
    t.column "post_counter",  :integer,  :default => 1,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
    t.column "is_distribute", :integer,  :default => 0
    t.column "source",        :string
    t.column "source_id",     :integer
    t.column "view_counter",  :integer,  :default => 1,  :null => false
  end

  add_index "ask_zhishi_topics", ["id"], :name => "index_zhishi_topic_id", :unique => true
  add_index "ask_zhishi_topics", ["subject"], :name => "index_zhishi_topic_subject"

  create_table "replies", :force => true do |t|
    t.column "area_id",        :integer
    t.column "type_id",        :integer
    t.column "entity_id",      :integer
    t.column "entity_summary", :text
    t.column "user_id",        :integer
    t.column "guest_email",    :string
    t.column "ip",             :string
    t.column "content",        :string
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "editor_id",      :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "tags", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "alias_id",   :integer
    t.column "parent_id",  :integer
    t.column "tag_level",  :integer
    t.column "tag_order",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "tags", ["id"], :name => "index_tag_id", :unique => true
  add_index "tags", ["name"], :name => "index_tag_name"

end
